server:
  port: 8001
spring:
  application:
    name: elysia-club-blog-service
  profiles:
    default: dev
  datasource:
    url: jdbc:mysql://${elysia.db.host}/elysia
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${elysia.db.username}
    password: ${elysia.db.password}
  cloud:
    nacos:
      server-addr: ${elysia.nacos.host}
      discovery:
        username: ${elysia.nacos.username}
        password: ${elysia.nacos.password}
        namespace: public
        ephemeral: true #nacos注册服务提供方设置为非临时实例